version: "3"

services:
  currency-db:
    container_name: "library_db3"
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - library-services:/var/lib/mysql2/data2
    ports:
      - "3306:3306"
  rabbitmq:
    image: rabbitmq:3.12.1-management-alpine
    container_name: 'rabbitmqLibrary3'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-enabled-plugins:/path/to/rabbitmq-enabled-plugins
#      - ./rabbitmq-defs.json:/etc/rabbitmq/rabbitmq-defs.json
#      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config

volumes:
  library-services:
  rabbitmq-enabled-plugins: